### ISSUE TITLE
UseRasCredentials - Processing

### ISSUE THREAD

**Issue by iamdevnull** [richardhicks/endpointmanager#1]
Hi Richard,

im trying to find an official technical explaination of the RAS phonebook Option UseRasCredentials without luck:

I found only: https://learn.microsoft.com/en-us/openspecs/windows_protocols/ms-rrasm/fcab274a-f4d1-49ad-bd81-aee790740e06

But this explains nothing.

I faced this Problem and Solution:

https://techsearch.watchguard.com/KB?type=Article&SFDCID=kA10H000000bpLuSAI&lang=en_US

I search over Google multiple docs

I ask myself the following question?

- which service/process/lib does technicaly read the Option UseRasCredentials?

**Comment by richardhicks** [comment]
Sadly there is very little (if any!) documentation for this setting. However, I would expect any process accessing resources over the VPN interface would be subject to this setting.
