### ISSUE TITLE
Remediate-AutoTriggerDisabledProfile.ps1 seems to be missing

### ISSUE THREAD

**Issue by Luke900** [richardhicks/endpointmanager#2]
Hi Richard,

Love your work, it has been a great help in troubleshooting issues with our AoVPN setuup.
Just noticed that there are 18 detect scripts here but only 17 remediate scripts. Remediate-AutoTriggerDisabledProfile.ps1 seems to be missing

I'd actually like to use that one, so is it available anywhere else?

Thanks,
Luke

**Comment by richardhicks** [comment]
Thanks for bringing this to my attention! As it turns out, simply removing that registry key does not restore automatic connection. There's some additional work required which I haven't completed. Once I do that, I'll upload both detection and remediation scripts. :)
