### ISSUE TITLE
TPM problems with RSAE-PSS ciphers - remediation creates new problem

### ISSUE THREAD

**Issue by Tarjei-stavanger** [richardhicks/endpointmanager#3]
We have noticed that removing the RSAE-PSS cyphers works for Wi-Fi with certificate logon.

However there seems to be issues with some other services which seems to require these ciphers for the user to log on. E.g. PowerBI.

So in general it is probably better to detect the issue than to blanket change the ciphers. We have tried that and are working on how to solve it.

**Comment by richardhicks** [comment]
Thanks for sharing this information. This guidance was provided to me by Microsoft, and they indicated that it could potentially cause problems. However, this is the first time I've encountered something not working after removing RSAE-PSS ciphers. Indeed, it would be best to apply this workaround only to systems that require it. For now, I will add a note about potential issues. 

Thanks!

**Comment by Tarjei-stavanger** [comment]
Sorry for reopening.  I have some additional information.

We have discovered that there is a few services that does not work with the fix. I don't think we have looked into the cryptography for communicating with these services yet.

I have a test PC which works fine with RSAE ciphers as long as it is running Windows 11. When I use Windows 10, it does not work on first logon with Wi-Fi and I have to log on using cable and then apply the fix for Wi-Fi to work.  I re-tank the PC between tests. I find it interesing that this PC has newer firmware and version number than my other test PC which only runs Windows 11. I will probably re-tank it with Windows 10 some time to see if it also has problems with Wi-Fi first logins with Windows 10.

I find it likely that the issue with the TPM is caused outside the TPM. Since someone reported that it worked fine with 1024 bit keys, it may well be that the issue is allocation of buffers. I find it certain that the problem is located in some interaction between windows/drivers and the TPM.

It may be that there is an actual problem with at least some TPMs.

**Comment by richardhicks** [comment]
No worries! Thanks for sharing your insight. I'm sure it will be helpful for others in the future. :) 

No question this issue is related to Windows and not the TPM hardware itself. Microsoft indicated the same when they provided this workaround for me. However, they made no mention that they were going to pursue a proper fix. Unfortunately, they usually don't when there is an easy workaround available. :/

**Comment by Tarjei-stavanger** [comment]
We have also discovered that there are Windows 11 machines which have the same problem. It really complicates our life.

Our impression is that it generally works on Windows 11, but not on all machines for some reason. Which might indicate that there is no real fix in Windows 11, just that "it works".

In any case, upgrading to Windows 11 is a fix for people with lots of money, but new hardware cost real money. Many businesses need to squeeze as much use of their gear as possible. So I have problems with Microsoft's attitude since they don't fix problems when there are still years of use left before the OS reaches end of life.

**Comment by richardhicks** [comment]
Good to know. Microsoft indicated to me it was potentially related to older TPM models, specifically those with sub-version 1.16 and earlier. Have a look at your devices and see if perhaps that's the common denominator.

**Comment by Tarjei-stavanger** [comment]
We are not buying Microsoft's explanation.

If we apply the fix to the encryption methods, we can log in with Wi-Fi EAP-TEAP on windows 10. But we can't log on to other services which requires the disabled encryption methods. This includes Microsoft supplied services.

If we keep the original settings, some of our people can't attach to the Wi-Fi with EAP-TEAP. But they can **ALL** log on to the services which requires the encryption methods we removed.

It is a mystery.
